require_relative './movements/slideable'
require_relative './movements/discrete'

require_relative 'piece.rb'
require_relative 'knight.rb'
require_relative 'bishop.rb'
require_relative 'rook.rb'
require_relative 'queen.rb'
require_relative 'king.rb'
require_relative 'pawn.rb'
